config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup' , to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  VALID_USER_NAME_REGEX = /\A(\w+)\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :user_name, presence: true,
                        length: { maximum: 30 },
                        uniqueness: { case_sensitive: false},
                        format: { with: VALID_USER_NAME_REGEX }
  validates :email, presence: true,
                    length: { maximum: 255 },
                    uniqueness: { case_sensitive: false},
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #登録成功時のアクション
      flash[:success] = "ユーザー登録が完了しました！"
      redirect_to @user
    else
      #登録失敗時のアクション
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    #ストロングパラメーター
    def user_params
      params.require(:user).permit(:user_name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #ページごとのタイトルを設定
  def full_title(page_title = "")
    base_title = "Knowledge Stocker"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #ユーザーからGravatarを返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.user_name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <nav>
      <ul class="nav-menu">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
    <ul class="sns">
      <li><%= link_to "Twitter", "https://twitter.com/toyokappa" %></li>
      <li><%= link_to "Facebook", "https://www.facebook.com/yuta.toyokawa" %></li>
      <li><%= link_to "GitHub", "https://github.com/toyokappa" %></li>
    </ul>
    <small>&copy; 2017 toyokappa.</small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <%= link_to "Knowledge Stocker", root_path, id: "logo" %>
    <nav>
      <ul class="nav-menu">
        <li><%= link_to "新規登録", signup_path %></li>
        <li><%= link_to "ログイン", "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{msg_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      <%= "入力エラー：#{@user.errors.count}項目" %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>効率よく用語を覚えるためのプラットフォームです。</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>ご意見、ご感想等がございましたらご連絡ください。</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Knowledge Stocker</h1>
  <h2>効率的かつ意欲的な学習体験を。</h2>
  <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<%= provide(:title, "新規登録") %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :user_name, "ユーザー名" %>
      <%= f.text_field :user_name, class: "form_control" %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: "form_control" %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: "form_control" %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: "form_control" %>

      <%= f.submit "登録する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<h1>ユーザー情報</h1>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user, size: 180 %>
      <div class="user_name"><%= @user.user_name %></div>
    </section>
  </aside>
</div>